// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/wagers": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/wagers";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/wagers.tsx": {
    id: "routes/wagers";
    page: "/wagers";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/wagers": typeof import("./app/routes/wagers.tsx");
};